### ISSUE TITLE
User Story 4

### ISSUE THREAD

**Issue by nazar0309** [nazar0309/RunningWalkthrough#4]
In order to **know whether users will join the race ** as an **administrator**, I can **add another section as a notification that reminds users about the upcoming race and asks if they will join it **

### Acceptance Criteria

1. User should be reminded only once a day 
2. Section should appear at the middle of website and should disappear after user will reply on it

### Tasks

- [ ]  Implement a design for section and choose the best position

- [ ]  Create it using HTML/CSS

- [ ]  Give it functionality to appear once a day and to ask users if they want to join a race using JS
- [ ]  Using DataBase, track how many users will join a race and delete it every day to get a new data
