### ISSUE TITLE
User Story 5

### ISSUE THREAD

**Issue by nazar0309** [nazar0309/RunningWalkthrough#5]
In order to **get information about the upcoming race** as a **user**, I can **fint it in a different section on another page of the website**

### Acceptance Criteria

1. Information about upcoming race should be on another page
2. It should contain the number of participators, time and location
3. It should write, whether the current user is going to participate or not

### Tasks

- [ ]  Implement a design for this page 
- [ ]  Create it using HTML/CSS
- [ ]  Give it a functionality using JS to get data to show location, time and number of participators
